blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & usage help
    url: https://community.home-assistant.io/t/packages-postnl-dhl-nl-dpd-and-gls-parcel-integration/112433/
    about: For setup questions and general discussion, please use the Home Assistant community thread.
